package mmconsultoria.co.mz.mbelamova.model;

public enum TripStatus {
    CLIENT_CONFIRMED, CLIENT_REJECTED, AVAILABLE, AWAITING_PAYMENT,DRIVER_CONFIRMED, CLIENT_CANCELED, DRIVER_CANCELED, CLIENT_REQUESTED, UNKNOWN, FINISHED, DRIVER_REJECTED, SCHEDULED, DRIVER_ARRIVED, IN_PROGRESS, DRIVER_GIVE_UP,CLIENT_GIVE_UP
}
